---
name: titanic-bat-director
director_uuid: f8f9e465-afe4-499e-9fa7-4c45c6be656d

disk_pools:
- name: disks
  disk_size: 15_000

resource_pools:
- name: vms
  network: vm-network
  stemcell:
    name: bosh-vsphere-esxi-ubuntu-trusty-go_agent
    version: 3120
  cloud_properties:
    cpu: 4
    ram: 4_096
    disk: 15_000
  env:
    bosh:
      # c1oudc0w is a default password for vcap user
      password: "$6$4gDD3aV0rdqlrKC$2axHCxGKIObs6tAmMTqYCspcdvQXh3JJcvWOY2WGb4SrdXtnCyNaWlrf3WEqvYR2MYizEGp3kMmbpwBC6jsHt0"

compilation:
  workers: 3
  network: vm-network
  reuse_compilation_vms: true
  cloud_properties:
    cpu: 4
    ram: 4_096
    disk: 15_000

update:
  canaries: 1
  max_in_flight: 1
  serial: false
  canary_watch_time: 1000-60000
  update_watch_time: 1000-60000

# replace all addresses with your network's IP range
#
# e.g. X.X.0.2 -> 10.0.0.2
networks:
  - name: vm-network
    type: manual
    subnets:
      - range: 192.168.0.0/16
        gateway: 192.168.10.1
        dns: [192.168.10.1]
        reserved: [192.168.0.2 - 192.168.9.255]
        static:
          - 192.168.10.219 - 192.168.10.219
        cloud_properties: {name: 'VM Network'}
  - name: rackhd-network
    type: manual
    subnets:
      - range: 172.31.128.0/22
        gateway: 172.31.128.1
        dns: [172.31.128.1]
        #reserved: [172.31.128.1-172.31.128.255]
        static:
          - 172.31.129.219 - 172.31.129.219
        cloud_properties: {name: 'OrangeBox Network1'}

releases:
  - name: bosh
    version: latest
  - name: titanic-rackhd-cpi
    version: latest

jobs:
- name: bosh
  instances: 1

  templates:
  - {name: nats, release: bosh}
  - {name: postgres, release: bosh}
  - {name: blobstore, release: bosh}
  - {name: director, release: bosh}
  - {name: health_monitor, release: bosh}
  - {name: rackhd-cpi, release: titanic-rackhd-cpi}

  resource_pool: vms
  persistent_disk_pool: disks

  networks:
  - {name: vm-network, static_ips: [192.168.10.219], default: [dns, gateway]}
  - {name: rackhd-network, static_ips: [172.31.129.219]}

  properties:
    nats:
      address: 127.0.0.1
      user: nats
      password: nats-password

    postgres: &db
      listen_address: 127.0.0.1
      host: 127.0.0.1
      user: postgres
      password: postgres-password
      database: bosh
      adapter: postgres

    blobstore:
      address: 192.168.10.219
      port: 25250
      use_ssl: false
      provider: dav
      director: {user: director, password: director-password}
      agent: {user: agent, password: agent-password}

    director:
      address: 127.0.0.1
      name: my-bosh
      db: *db
      cpi_job: rackhd-cpi
      user_management:
        provider: local
        local:
          users:
          - {name: admin, password: admin}
          - {name: hm, password: hm-password}

    hm:
      director_account: {user: hm, password: hm-password}
      resurrector_enabled: true

    rackhd-cpi:
      apiserver: "192.168.0.134"
      agent:
        mbus: "nats://nats:nats-password@172.31.129.219:4222"
        blobstore:
          provider: dav
          options:
            endpoint: http://172.31.129.219:25250
            user: agent
            password: agent-password

    agent: {mbus: "nats://nats:nats-password@172.31.129.219:4222"}

    ntp: &ntp [0.pool.ntp.org, 1.pool.ntp.org]

cloud_provider:
  template: {name: rackhd-cpi, release: titanic-rackhd-cpi}
  mbus: "https://mbus:mbus-password@172.31.129.219:6868"

  properties:
    rackhd-cpi:
      apiserver: "192.168.0.134"
      agent:
        mbus: "https://mbus:Pbc7ssdfh8w2@0.0.0.0:6868"
        blobstore:
          provider: local
          options: {blobstore_path: /var/vcap/micro_bosh/data/cache}
