---
groups:
  - name: bosh-rackhd-cpi
    jobs:
      - integration
      - lifecycle
      - bats-centos
      - bats-ubuntu
      - setup-director
      - teardown-director
      - promote-candidate

jobs:
- name: integration
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true,   get: bosh-cpi-release,     resource: bosh-rackhd-cpi-release}
  - task: test
    file: bosh-cpi-release/ci/tasks/integration.yml
    config:
      params:
        RACKHD_API_URI:              {{rackhd_server_ip}}

- name: lifecycle
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true,  passed: [integration],  get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false,                         get: stemcell,           resource: rackhd-openstack-ubuntu-stemcell}
  - put: emccmd-env-lifecycle
    params: {acquire: true}
  - task: test
    file: bosh-cpi-release/ci/tasks/lifecycle.yml
    config:
      params:
        RACKHD_API_URI:               {{rackhd_server_ip}}
        AGENT_PUBLIC_KEY:             {{agent_public_key}}
        STATIC_IP:                    {{lifecycle_static_ip}}
        GATEWAY:                      {{gateway}}
    ensure:
      put: emccmd-env-lifecycle
      params: {release: emccmd-env-lifecycle}

- name: setup-director
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true,  passed: [lifecycle], get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false,                      get: bosh-release,       resource: bosh-release}
  - task: setup-director
    file: bosh-cpi-release/ci/tasks/setup-director.yml
    config:
      params:
        BOSH_VSPHERE_DIRECTOR:              {{bosh_vsphere_director}}
        BOSH_DIRECTOR_PUBLIC_IP:            {{bosh_director_public_ip}}
        BOSH_DIRECTOR_PRIVATE_IP:           {{bosh_director_private_ip}}
        BOSH_DIRECTOR_PUBLIC_KEY:           {{director_public_key}}
        RACKHD_API_URI:                     {{rackhd_server_ip}}
        RACKHD_NETWORK:                     {{rackhd_network}}
        CPI_RELEASE_NAME:                   {{cpi_release_name}}
        DIRECTOR_DEPLOYMENT_NAME:           {{director_deployment_name}}

- name: bats-centos
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true,  passed: [setup-director],    get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false,                              get: stemcell,           resource: rackhd-openstack-centos-stemcell}
    - {trigger: false,                              get: bats,               resource: bosh-acceptance-tests}
  - put: emccmd-env-bats
    params: {acquire: true}
  - task: test
    file: bosh-cpi-release/ci/tasks/bats.yml
    config:
      params:
        AGENT_PUBLIC_KEY:                   {{agent_public_key}}
        DIRECTOR_PRIVATE_KEY_DATA:          {{director_private_key}}
        BOSH_DIRECTOR_PUBLIC_IP:            {{bosh_director_public_ip}}
        BOSH_DIRECTOR_PRIVATE_IP:           {{bosh_director_private_ip}}
        PRIMARY_NETWORK_CIDR:               {{centos_primary_network_cidr}}
        PRIMARY_NETWORK_GATEWAY:            {{centos_primary_network_gateway}}
        PRIMARY_NETWORK_RANGE:              {{centos_primary_network_range}}
        PRIMARY_NETWORK_MANUAL_IP:          {{centos_primary_network_manual_ip}}
        SECONDARY_STATIC_IP:                {{centos_secondary_static_ip}}
        BAT_SPEC:                           {{bat_spec}}
        BAT_STEMCELL_NAME:                  bosh-openstack-kvm-centos-7-go_agent-raw
        BAT_DEPLOYMENT_NAME:                bat-centos
    ensure:
      put: emccmd-env-bats
      params: {release: emccmd-env-bats}

- name: bats-ubuntu
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true,  passed: [setup-director],    get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false,                              get: stemcell,           resource: rackhd-openstack-ubuntu-stemcell}
    - {trigger: false,                              get: bats,               resource: bosh-acceptance-tests}
  - put: emccmd-env-bats
    params: {acquire: true}
  - task: test
    file: bosh-cpi-release/ci/tasks/bats.yml
    config:
      params:
        AGENT_PUBLIC_KEY:                   {{agent_public_key}}
        DIRECTOR_PRIVATE_KEY_DATA:          {{director_private_key}}
        BOSH_DIRECTOR_PUBLIC_IP:            {{bosh_director_public_ip}}
        BOSH_DIRECTOR_PRIVATE_IP:           {{bosh_director_private_ip}}
        PRIMARY_NETWORK_CIDR:               {{ubuntu_primary_network_cidr}}
        PRIMARY_NETWORK_GATEWAY:            {{ubuntu_primary_network_gateway}}
        PRIMARY_NETWORK_RANGE:              {{ubuntu_primary_network_range}}
        PRIMARY_NETWORK_MANUAL_IP:          {{ubuntu_primary_network_manual_ip}}
        SECONDARY_STATIC_IP:                {{ubuntu_secondary_static_ip}}
        BAT_SPEC:                           {{bat_spec}}
        BAT_STEMCELL_NAME:                  bosh-openstack-kvm-ubuntu-trusty-go_agent-raw
        BAT_DEPLOYMENT_NAME:                bat-ubuntu
    ensure:
      put: emccmd-env-bats
      params: {release: emccmd-env-bats}

- name: teardown-director
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true, passed: [bats-centos, bats-ubuntu], get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
  - task: teardown-director
    file: bosh-cpi-release/ci/tasks/teardown-director.yml
    config:
      params:
        BOSH_VSPHERE_DIRECTOR:              {{bosh_vsphere_director}}
        CPI_RELEASE_NAME:                   {{cpi_release_name}}
        DIRECTOR_DEPLOYMENT_NAME:           {{director_deployment_name}}

- name: promote-candidate
  serial: true
  serial_groups: ["rackhd-ci"]
  plan:
  - aggregate:
    - {trigger: true, passed: [bats-centos, bats-ubuntu], get: bosh-cpi-release,   resource: bosh-rackhd-cpi-release}
    - {trigger: false,                          get: release-version-semver,  params: {bump: major}}

  - task: promote
    file: bosh-cpi-release/ci/tasks/promote-candidate.yml
    config:
      params:
        S3_ACCESS_KEY_ID:     {{s3_access_key_id}}
        S3_SECRET_ACCESS_KEY: {{s3_secret_access_key}}
  - put: bosh-cpi-release-out
    params: {repository: promote/bosh-cpi-release, rebase: true, tag_prefix: "v", tag: promote/integer_version}

  - put: release-version-semver
    params: {file: release-version-semver/number}


resources:
  - &bosh-cpi-release-resource
    name: bosh-rackhd-cpi-release
    type: git
    source:
      uri: git@github.com:EMC-CMD/bosh-rackhd-cpi-release.git
      branch: master
      private_key: {{github_key__bosh-rackhd-cpi-release}}
      ignore_paths:
        - .final_builds/**/*.yml
        - releases/**/*.yml

  - <<: *bosh-cpi-release-resource
    name: bosh-cpi-release-out

  - name: rackhd-openstack-ubuntu-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-openstack-kvm-ubuntu-trusty-go_agent-raw

  - name: rackhd-openstack-centos-stemcell
    type: bosh-io-stemcell
    source:
      name: bosh-openstack-kvm-centos-7-go_agent-raw

  - name: bosh-acceptance-tests
    type: git
    source:
      uri: git@github.com:EMC-CMD/bosh-acceptance-tests.git
      branch: pr-coretag
      private_key: {{github_key__bosh-acceptance-tests}}

  - name: emccmd-env-lifecycle
    type: pool
    source:
      uri: git@github.com:EMC-CMD/emccmd-environments.git
      branch: master
      pool: lifecycle
      private_key: {{github_key__emccmd-environments}}

  - name: emccmd-env-bats
    type: pool
    source:
      uri: git@github.com:EMC-CMD/emccmd-environments.git
      branch: master
      pool: bats
      private_key: {{github_key__emccmd-environments}}

  - name: release-version-semver
    type: semver
    source:
      key:               release-current-version
      bucket:            {{s3_bucket_name}}
      access_key_id:     {{s3_access_key_id}}
      secret_access_key: {{s3_secret_access_key}}

  - name: bosh-release
    type: bosh-io-release
    source:
      repository: cloudfoundry/bosh
